name: Pull & push actions

on:
  pull_request:
  push:
    branches:
      - master
      - dev
    paths-ignore:
    - '.github/workflows/**'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v4.1.5"

        - name: HACS Action
          uses: "hacs/action@main"
          with:
            category: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v4.1.5"
        - uses: "actions/setup-python@v5.1.0"
          with:
            python-version: "3.x"
        - run: python3 -m pip install black
        - run: black .
